---
- name: add mariadb repository
  template:
    src: MariaDB.repo
    dest: /etc/yum.repos.d/MariaDB.repo
- name: install mariadb
  yum:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MySQL-python
    - mariadb-devel
- name: start mariadb
  service: name=mysql enabled=yes state=started
- name: add maria database users
  mysql_user:
    name: "{{project_name}}"
    password: "{{project_name}}"
    host: localhost
    priv: "*.*:ALL"
    state: present

- name: create project_name database
  mysql_db:
    name: "{{item}}"
    state: present
  with_items: "{{databases}}"
