project_name: ocracoke

rvm1_rubies:
  - ruby-2.3.1
rvm1_bundler_install: True
rvm1_user: 'vagrant'
rvm1_rvm_version: 'stable'
rvm1_autolib_mode: 3

redis_appendonly: "yes"

solr_version: "8.2.0"
solr_create_user: true
solr_user: vagrant
solr_remove_cruft: true
solr_port: "8983"
solr_connect_host: localhost
solr_cores:
  - ocracoke

mysql_root_password: 'mysqlrootpassword'
mysql_databases:
  - name: ocracoke
    encoding: utf8
  - name: test
    encoding: utf8
mysql_users:
  - name: ocracoke
    host: '%'
    password: 'ocracoke'
    priv: 'ocracoke.*:ALL'
