---
- name: install epel-release
  yum:
    name: epel-release
    state: present
- name: install required packages
  yum:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - git-core
    - curl
    - zlib
    - zlib-devel
    - gcc-c++
    - readline
    - readline-devel
    - libyaml-devel
    - libffi-devel
    - openssl-devel
    - make
    - bzip2
    - autoconf
    - automake
    - libtool
    - bison
    - sqlite
    - sqlite-devel
    - libxml2-devel
    - libxslt-devel
    - libcurl-devel
    - nodejs
    - httpd
    - httpd-devel
    - nano
    - tree
    - htop
