---
- name: install epel-release
  yum:
    name: epel-release
    state: present
- name: install required packages
  yum:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm
    - https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-devel-2.7.1-3.el7.x86_64.rpm
    - kernel-headers
    - kernel-devel
    - git-core
    - curl
    - zlib
    - zlib-devel
    - gcc-c++
    - readline
    - readline-devel
    - libyaml-devel
    - libffi-devel
    - openssl-devel
    - make
    - bzip2
    - autoconf
    - automake
    - libtool
    - bison
    - sqlite
    - sqlite-devel
    - libxml2-devel
    - libxslt-devel
    - libcurl-devel
    - nodejs
    - httpd
    - httpd-devel
    - nano
    - tree
    - htop
