default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: ocracoke
  username: ocracoke
  password: ocracoke

# test:
#   <<: *default
#   database: ocr_test
#   username: ocr
#   password: ocr
