development:
  ocr_directory: /access-images/ocr/
  iiif_base_url: https://iiif-staging02.lib.ncsu.edu/iiif
  ocracoke_base_url: "https://ocr-staging01.lib.ncsu.edu/ocr/"
  canvas_url_template: "http://scrc.lib.ncsu.edu/sal_staging/canvas/{id}"
  solr_url: http://localhost:8983/solr/ocracoke
  notification: false
    # url: http://<%= `netstat -rn | grep "^0.0.0.0 " | cut -d " " -f10`.chomp %>:3000/api_incoming/ocr
    # token: token_for_ocr_app
