---
galaxy_info:
  author: Nick Janetakis
  description: The official rvm role to install and manage your ruby versions.
  company: ''
  license: license (MIT)
  min_ansible_version: 2.2

  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - development
    - web

dependencies: []
