---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: root
  gather_facts: yes
  vars_files:
    - vars/main.yml
  pre_tasks:
    - yum:
        pkg: "mysql-devel"
        state: present
        update_cache: yes
  roles:
    - role: basic-setup
    - role: rvm.ruby
    - role: geerlingguy.mysql
      databases:
        - "{{project_name}}"
        - "{{project_name}}_test"
    - role: geerlingguy.redis
    - role: geerlingguy.java
      version: 1.8.0
    - role: geerlingguy.solr
    - role: ocr
  post_tasks:
    # These post_tasks are to create the same directories as exist on the
    # production server so that we can actually try this out!
    # Make them wide-open just to make it easier.
    - name: create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "u=rwx,g=rwx,o=rwx"
      with_items:
        - /access-images/ocr
        - /access-images/cache
