---
- hosts: iiifsi
  become: yes
  become_method: sudo
  become_user: root
  remote_user: root
  gather_facts: yes
  roles:
    - role: basic-setup
    - role: dev-open-firewall
      ports:
        - 443
        - 80
        - 3000
        - 8983
    - role: ocr
    - role: rvm_io.rvm1-ruby
      rvm1_rubies:
        - ruby-2.3.0
    - role: rvm-setup
      users:
        - vagrant
    - role: geerlingguy.redis
      redis_appendonly: "yes"
    - role: java
      version: 1.8.0
    - role: solr
      version: 6.1.0
      port: 8983
      service_name: solr-iiifsi
      confdir: /vagrant/solr_conf
      cores:
        - iiifsi
      group: vagrant
  post_tasks:
    # These post_tasks are to create the same directories as exist on the
    # production server so that we can actually try this out!
    # Make them wide-open just to make it easier.
    - name: create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "u=rwx,g=rwx,o=rwx"
      with_items:
        - /access-images/ocr
