---
- name: install lsof
  yum:
    pkg: lsof
    state: latest
- name: download solr
  get_url:
    url: http://archive.apache.org/dist/lucene/solr/{{version}}/solr-{{version}}.tgz
    dest: ~/solr-{{version}}.tgz
- name: untar solr
  unarchive:
    copy: no
    # owner: vagrant
    # group: vagrant
    src: ~/solr-{{version}}.tgz
    dest: ~/.
- name: install solr service
  shell: bin/install_solr_service.sh ~/solr-{{version}}.tgz -f chdir=~/solr-{{version}} -p {{port}} -s {{service_name}}
- name: move solr files to /home/solr
  shell: mv ~/solr-{{version}} /home/solr/.
  args:
    creates: /home/solr/solr-{{version}}
- name: solr should own solr binaries
  file:
    path: /home/solr/solr-{{version}}
    owner: solr
    recurse: yes
- name: add solr user to deploy group
  user:
    name: solr
    group: solr
    groups: "{{group}}"
    append: yes
- name: confdir should be readable by deploy group
  file:
    path: "{{confdir}}"
    recurse: yes
    group: "{{group}}"
    mode: "g+rX"
- name: create core
  become_user: solr
  shell: bin/solr create -c "{{item}}" -d "{{confdir}}"
  args:
    chdir: ~/solr-{{version}}
  with_items: "{{cores}}"
- name: remove conf directory
  become_user: solr
  file:
    path: /var/{{service_name}}/data/{{item}}/conf
    state: absent
  with_items: "{{cores}}"
- name: symlink confdir
  become_user: solr
  file:
    src: "{{confdir}}"
    dest: /var/{{service_name}}/data/{{item}}/conf
    state: link
  with_items: "{{cores}}"
